# Generated by Django 5.1 on 2024-08-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieinfo",
            old_name="description",
            new_name="summary",
        ),
    ]
